name: Tests

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    tests:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: 'Tests'
                        run: vendor/bin/phpunit

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: ${{ matrix.actions.run }}
