name: Tests

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    tests:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    # for some reason they have to be run separately, otherwise autoload messes up
                    -
                        name: 'Tests Rules'
                        run: vendor/bin/phpunit --testsuite rules

                    -
                        name: 'Tests Extensions'
                        run: vendor/bin/phpunit --testsuite extensions

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: ${{ matrix.actions.run }}
